version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports: 
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: 
      - production

  web:
    build:
      dockerfile: ./docker/python.dockerfile
      context: .
    image: diemesleno/python
    container_name: python
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks: 
      - production
    depends_on:
      - "db"

volumes:
   pgdata:
networks:
   production:
      driver: bridge