version: '3.2'

services:
  db:
    image: postgres
    ports: 
      - "5432"
    networks: 
      - production

  web:
    build:
      dockerfile: ./docker/python.dockerfile
      context: .
    image: diemesleno/python
    container_name: python
    command: python manage.py runserver 0.0.0.0:8000       
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks: 
      - production
    depends_on:
      - "migration"

  migration:
    build:
      dockerfile: ./docker/python.dockerfile
      context: .
    image: diemesleno/django
    container_name: django
    command: python manage.py migrate --noinput
    networks: 
      - production
    depends_on:
      - "db"

networks:
   production:
      driver: bridge